server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgres://user_01:Abcd123456@pgm-wz9rmi446k4v4tje4o.pg.rds.aliyuncs.com:1921/dev?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
tracing:
  endpoint: http://tracing-cn-guangzhou.arms.aliyuncs.com/adapt_atma6tpxtr@5f4c0b1eba3cd97_atma6tpxtr@53df7ad2afe8301/api/traces
#  endpoint: http://192.168.30.21:14268/api/traces