// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Casper-Mars/cloud-restaurant/app/comment/internal/data/ent/comment"
	"github.com/Casper-Mars/cloud-restaurant/app/comment/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreateTime is the schema descriptor for createTime field.
	commentDescCreateTime := commentFields[0].Descriptor()
	// comment.DefaultCreateTime holds the default value on creation for the createTime field.
	comment.DefaultCreateTime = commentDescCreateTime.Default.(func() time.Time)
	// commentDescUpdateTime is the schema descriptor for updateTime field.
	commentDescUpdateTime := commentFields[1].Descriptor()
	// comment.DefaultUpdateTime holds the default value on creation for the updateTime field.
	comment.DefaultUpdateTime = commentDescUpdateTime.Default.(func() time.Time)
	// comment.UpdateDefaultUpdateTime holds the default value on update for the updateTime field.
	comment.UpdateDefaultUpdateTime = commentDescUpdateTime.UpdateDefault.(func() time.Time)
	// commentDescDeleteFlag is the schema descriptor for delete_flag field.
	commentDescDeleteFlag := commentFields[2].Descriptor()
	// comment.DefaultDeleteFlag holds the default value on creation for the delete_flag field.
	comment.DefaultDeleteFlag = commentDescDeleteFlag.Default.(bool)
}
