// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsGenError(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GEN_ERROR.String() && e.Code == 500
}

func ErrorGenError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_GEN_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsParamMiss(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PARAM_MISS.String() && e.Code == 504
}

func ErrorParamMiss(format string, args ...interface{}) *errors.Error {
	return errors.New(504, ErrorReason_PARAM_MISS.String(), fmt.Sprintf(format, args...))
}
