// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/interface/v1/food.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddFoodReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AddFoodReq) Reset() {
	*x = AddFoodReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_interface_v1_food_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFoodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFoodReq) ProtoMessage() {}

func (x *AddFoodReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_interface_v1_food_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFoodReq.ProtoReflect.Descriptor instead.
func (*AddFoodReq) Descriptor() ([]byte, []int) {
	return file_api_interface_v1_food_proto_rawDescGZIP(), []int{0}
}

func (x *AddFoodReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FoodModifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FoodModifyResp) Reset() {
	*x = FoodModifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_interface_v1_food_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoodModifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodModifyResp) ProtoMessage() {}

func (x *FoodModifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_interface_v1_food_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodModifyResp.ProtoReflect.Descriptor instead.
func (*FoodModifyResp) Descriptor() ([]byte, []int) {
	return file_api_interface_v1_food_proto_rawDescGZIP(), []int{1}
}

func (x *FoodModifyResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FoodList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*FoodList_FoodListItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *FoodList) Reset() {
	*x = FoodList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_interface_v1_food_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoodList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodList) ProtoMessage() {}

func (x *FoodList) ProtoReflect() protoreflect.Message {
	mi := &file_api_interface_v1_food_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodList.ProtoReflect.Descriptor instead.
func (*FoodList) Descriptor() ([]byte, []int) {
	return file_api_interface_v1_food_proto_rawDescGZIP(), []int{2}
}

func (x *FoodList) GetItems() []*FoodList_FoodListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type FoodList_FoodListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FoodList_FoodListItem) Reset() {
	*x = FoodList_FoodListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_interface_v1_food_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoodList_FoodListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodList_FoodListItem) ProtoMessage() {}

func (x *FoodList_FoodListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_interface_v1_food_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodList_FoodListItem.ProtoReflect.Descriptor instead.
func (*FoodList_FoodListItem) Descriptor() ([]byte, []int) {
	return file_api_interface_v1_food_proto_rawDescGZIP(), []int{2, 0}
}

func (x *FoodList_FoodListItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FoodList_FoodListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_interface_v1_food_proto protoreflect.FileDescriptor

var file_api_interface_v1_food_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x46, 0x6f, 0x6f,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x46, 0x6f, 0x6f, 0x64,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x79, 0x0a, 0x08, 0x46, 0x6f,
	0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x46, 0x6f,
	0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x1a, 0x32, 0x0a, 0x0c, 0x46, 0x6f, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xa7, 0x01, 0x0a, 0x04, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x53,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x18, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x6f, 0x6f, 0x64,
	0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x22, 0x05, 0x2f, 0x66, 0x6f, 0x6f, 0x64,
	0x3a, 0x01, 0x2a, 0x12, 0x4a, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x12, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x66, 0x6f, 0x6f, 0x64, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42,
	0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x61,
	0x73, 0x70, 0x65, 0x72, 0x2d, 0x4d, 0x61, 0x72, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d,
	0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_interface_v1_food_proto_rawDescOnce sync.Once
	file_api_interface_v1_food_proto_rawDescData = file_api_interface_v1_food_proto_rawDesc
)

func file_api_interface_v1_food_proto_rawDescGZIP() []byte {
	file_api_interface_v1_food_proto_rawDescOnce.Do(func() {
		file_api_interface_v1_food_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_interface_v1_food_proto_rawDescData)
	})
	return file_api_interface_v1_food_proto_rawDescData
}

var file_api_interface_v1_food_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_interface_v1_food_proto_goTypes = []interface{}{
	(*AddFoodReq)(nil),            // 0: interface.v1.AddFoodReq
	(*FoodModifyResp)(nil),        // 1: interface.v1.FoodModifyResp
	(*FoodList)(nil),              // 2: interface.v1.FoodList
	(*FoodList_FoodListItem)(nil), // 3: interface.v1.FoodList.FoodListItem
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_api_interface_v1_food_proto_depIdxs = []int32{
	3, // 0: interface.v1.FoodList.items:type_name -> interface.v1.FoodList.FoodListItem
	0, // 1: interface.v1.Food.AddFood:input_type -> interface.v1.AddFoodReq
	4, // 2: interface.v1.Food.List:input_type -> google.protobuf.Empty
	1, // 3: interface.v1.Food.AddFood:output_type -> interface.v1.FoodModifyResp
	2, // 4: interface.v1.Food.List:output_type -> interface.v1.FoodList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_interface_v1_food_proto_init() }
func file_api_interface_v1_food_proto_init() {
	if File_api_interface_v1_food_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_interface_v1_food_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFoodReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_interface_v1_food_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoodModifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_interface_v1_food_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoodList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_interface_v1_food_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoodList_FoodListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_interface_v1_food_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_interface_v1_food_proto_goTypes,
		DependencyIndexes: file_api_interface_v1_food_proto_depIdxs,
		MessageInfos:      file_api_interface_v1_food_proto_msgTypes,
	}.Build()
	File_api_interface_v1_food_proto = out.File
	file_api_interface_v1_food_proto_rawDesc = nil
	file_api_interface_v1_food_proto_goTypes = nil
	file_api_interface_v1_food_proto_depIdxs = nil
}
