// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Casper-Mars/cloud-restaurant/interface/internal/biz"
	"github.com/Casper-Mars/cloud-restaurant/interface/internal/conf"
	"github.com/Casper-Mars/cloud-restaurant/interface/internal/server"
	"github.com/Casper-Mars/cloud-restaurant/interface/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	userClient := biz.NewUserClient()
	authUsecase := biz.NewAuthUsecase(logger, userClient)
	authService := service.NewAuthService(authUsecase, logger)
	healthUsecase := biz.NewHealthUsecase(userClient)
	healthService := service.NewHealthService(healthUsecase)
	httpServer := server.NewHTTPServer(confServer, logger, authService, healthService)
	grpcServer := server.NewGRPCServer(confServer, authService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
