// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Casper-Mars/cloud-restaurant/app/interface/internal/biz"
	"github.com/Casper-Mars/cloud-restaurant/app/interface/internal/conf"
	"github.com/Casper-Mars/cloud-restaurant/app/interface/internal/server"
	"github.com/Casper-Mars/cloud-restaurant/app/interface/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	userClient := biz.NewUserClient()
	authUsecase := biz.NewAuthUsecase(logger, userClient)
	authService := service.NewAuthService(authUsecase, logger)
	healthUsecase := biz.NewHealthUsecase(userClient)
	healthService := service.NewHealthService(healthUsecase)
	userUsecase := biz.NewUserUsecase(userClient)
	userService := service.NewUserService(userUsecase)
	foodClient := biz.NewFoodClient()
	foodUsecase := biz.NewFoodUsecase(logger, foodClient)
	foodService := service.NewFoodService(logger, foodUsecase)
	commentClient := biz.NewCommentClient()
	commentUsecase := biz.NewCommentUsecase(logger, userClient, foodClient, commentClient)
	commentService := service.NewCommentService(commentUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, authService, healthService, userService, foodService, commentService)
	grpcServer := server.NewGRPCServer(confServer, authService, userService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
