// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Casper-Mars/cloud-restaurant/app/interface/internal/biz"
	"github.com/Casper-Mars/cloud-restaurant/app/interface/internal/conf"
	"github.com/Casper-Mars/cloud-restaurant/app/interface/internal/server"
	"github.com/Casper-Mars/cloud-restaurant/app/interface/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	authUsecase := biz.NewAuthUsecase(logger)
	authService := service.NewAuthService(authUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, authService)
	grpcServer := server.NewGRPCServer(confServer, authService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
