// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/food/v1/food.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ListFoodByIdReq with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *ListFoodByIdReq) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// ListFoodByIdReqValidationError is the validation error returned by
// ListFoodByIdReq.Validate if the designated constraints aren't met.
type ListFoodByIdReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListFoodByIdReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListFoodByIdReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListFoodByIdReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListFoodByIdReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListFoodByIdReqValidationError) ErrorName() string { return "ListFoodByIdReqValidationError" }

// Error satisfies the builtin error interface
func (e ListFoodByIdReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListFoodByIdReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListFoodByIdReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListFoodByIdReqValidationError{}

// Validate checks the field values on AddFoodReq with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *AddFoodReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	// no validation rules for Price

	return nil
}

// AddFoodReqValidationError is the validation error returned by
// AddFoodReq.Validate if the designated constraints aren't met.
type AddFoodReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddFoodReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddFoodReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddFoodReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddFoodReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddFoodReqValidationError) ErrorName() string { return "AddFoodReqValidationError" }

// Error satisfies the builtin error interface
func (e AddFoodReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddFoodReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddFoodReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddFoodReqValidationError{}

// Validate checks the field values on UpdateFoodReq with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *UpdateFoodReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Price

	return nil
}

// UpdateFoodReqValidationError is the validation error returned by
// UpdateFoodReq.Validate if the designated constraints aren't met.
type UpdateFoodReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateFoodReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateFoodReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateFoodReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateFoodReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateFoodReqValidationError) ErrorName() string { return "UpdateFoodReqValidationError" }

// Error satisfies the builtin error interface
func (e UpdateFoodReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateFoodReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateFoodReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateFoodReqValidationError{}

// Validate checks the field values on FoodModifyResp with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *FoodModifyResp) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	return nil
}

// FoodModifyRespValidationError is the validation error returned by
// FoodModifyResp.Validate if the designated constraints aren't met.
type FoodModifyRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FoodModifyRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FoodModifyRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FoodModifyRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FoodModifyRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FoodModifyRespValidationError) ErrorName() string { return "FoodModifyRespValidationError" }

// Error satisfies the builtin error interface
func (e FoodModifyRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFoodModifyResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FoodModifyRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FoodModifyRespValidationError{}

// Validate checks the field values on OnePageFoodListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *OnePageFoodListReq) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetPageIndex()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OnePageFoodListReqValidationError{
				field:  "PageIndex",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetPageSize()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OnePageFoodListReqValidationError{
				field:  "PageSize",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Name

	return nil
}

// OnePageFoodListReqValidationError is the validation error returned by
// OnePageFoodListReq.Validate if the designated constraints aren't met.
type OnePageFoodListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OnePageFoodListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OnePageFoodListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OnePageFoodListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OnePageFoodListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OnePageFoodListReqValidationError) ErrorName() string {
	return "OnePageFoodListReqValidationError"
}

// Error satisfies the builtin error interface
func (e OnePageFoodListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOnePageFoodListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OnePageFoodListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OnePageFoodListReqValidationError{}

// Validate checks the field values on FoodListResp with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *FoodListResp) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FoodListRespValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// FoodListRespValidationError is the validation error returned by
// FoodListResp.Validate if the designated constraints aren't met.
type FoodListRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FoodListRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FoodListRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FoodListRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FoodListRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FoodListRespValidationError) ErrorName() string { return "FoodListRespValidationError" }

// Error satisfies the builtin error interface
func (e FoodListRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFoodListResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FoodListRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FoodListRespValidationError{}

// Validate checks the field values on FoodListResp_FoodItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *FoodListResp_FoodItem) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Price

	return nil
}

// FoodListResp_FoodItemValidationError is the validation error returned by
// FoodListResp_FoodItem.Validate if the designated constraints aren't met.
type FoodListResp_FoodItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FoodListResp_FoodItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FoodListResp_FoodItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FoodListResp_FoodItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FoodListResp_FoodItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FoodListResp_FoodItemValidationError) ErrorName() string {
	return "FoodListResp_FoodItemValidationError"
}

// Error satisfies the builtin error interface
func (e FoodListResp_FoodItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFoodListResp_FoodItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FoodListResp_FoodItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FoodListResp_FoodItemValidationError{}
