// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Casper-Mars/cloud-restaurant/app/comment/internal/biz"
	"github.com/Casper-Mars/cloud-restaurant/app/comment/internal/conf"
	"github.com/Casper-Mars/cloud-restaurant/app/comment/internal/data"
	"github.com/Casper-Mars/cloud-restaurant/app/comment/internal/server"
	"github.com/Casper-Mars/cloud-restaurant/app/comment/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	commentRepo := data.NewCommentRepo(dataData, logger)
	commentUsecase := biz.NewCommentUsecase(commentRepo, logger)
	commentService := service.NewCommentService(commentUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, commentService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
