apiVersion: v1
kind: Service
metadata:
  name: {{ include "food.fullname" . }}
  labels:
    {{- include "food.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: gprc
      protocol: TCP
      name: gprc
  selector:
    {{- include "food.selectorLabels" . | nindent 4 }}
