// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Casper-Mars/cloud-restaurant/app/food/internal/data/ent/food"
)

// FoodCreate is the builder for creating a Food entity.
type FoodCreate struct {
	config
	mutation *FoodMutation
	hooks    []Hook
}

// SetCreateTime sets the "createTime" field.
func (fc *FoodCreate) SetCreateTime(t time.Time) *FoodCreate {
	fc.mutation.SetCreateTime(t)
	return fc
}

// SetNillableCreateTime sets the "createTime" field if the given value is not nil.
func (fc *FoodCreate) SetNillableCreateTime(t *time.Time) *FoodCreate {
	if t != nil {
		fc.SetCreateTime(*t)
	}
	return fc
}

// SetUpdateTime sets the "updateTime" field.
func (fc *FoodCreate) SetUpdateTime(t time.Time) *FoodCreate {
	fc.mutation.SetUpdateTime(t)
	return fc
}

// SetNillableUpdateTime sets the "updateTime" field if the given value is not nil.
func (fc *FoodCreate) SetNillableUpdateTime(t *time.Time) *FoodCreate {
	if t != nil {
		fc.SetUpdateTime(*t)
	}
	return fc
}

// SetDeleteFlag sets the "delete_flag" field.
func (fc *FoodCreate) SetDeleteFlag(b bool) *FoodCreate {
	fc.mutation.SetDeleteFlag(b)
	return fc
}

// SetNillableDeleteFlag sets the "delete_flag" field if the given value is not nil.
func (fc *FoodCreate) SetNillableDeleteFlag(b *bool) *FoodCreate {
	if b != nil {
		fc.SetDeleteFlag(*b)
	}
	return fc
}

// SetName sets the "name" field.
func (fc *FoodCreate) SetName(s string) *FoodCreate {
	fc.mutation.SetName(s)
	return fc
}

// SetID sets the "id" field.
func (fc *FoodCreate) SetID(u uint64) *FoodCreate {
	fc.mutation.SetID(u)
	return fc
}

// Mutation returns the FoodMutation object of the builder.
func (fc *FoodCreate) Mutation() *FoodMutation {
	return fc.mutation
}

// Save creates the Food in the database.
func (fc *FoodCreate) Save(ctx context.Context) (*Food, error) {
	var (
		err  error
		node *Food
	)
	fc.defaults()
	if len(fc.hooks) == 0 {
		if err = fc.check(); err != nil {
			return nil, err
		}
		node, err = fc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FoodMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = fc.check(); err != nil {
				return nil, err
			}
			fc.mutation = mutation
			node, err = fc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(fc.hooks) - 1; i >= 0; i-- {
			mut = fc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FoodCreate) SaveX(ctx context.Context) *Food {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (fc *FoodCreate) defaults() {
	if _, ok := fc.mutation.CreateTime(); !ok {
		v := food.DefaultCreateTime()
		fc.mutation.SetCreateTime(v)
	}
	if _, ok := fc.mutation.UpdateTime(); !ok {
		v := food.DefaultUpdateTime()
		fc.mutation.SetUpdateTime(v)
	}
	if _, ok := fc.mutation.DeleteFlag(); !ok {
		v := food.DefaultDeleteFlag
		fc.mutation.SetDeleteFlag(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FoodCreate) check() error {
	if _, ok := fc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "createTime", err: errors.New("ent: missing required field \"createTime\"")}
	}
	if _, ok := fc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "updateTime", err: errors.New("ent: missing required field \"updateTime\"")}
	}
	if _, ok := fc.mutation.DeleteFlag(); !ok {
		return &ValidationError{Name: "delete_flag", err: errors.New("ent: missing required field \"delete_flag\"")}
	}
	if _, ok := fc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	return nil
}

func (fc *FoodCreate) sqlSave(ctx context.Context) (*Food, error) {
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	if _node.ID == 0 {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	return _node, nil
}

func (fc *FoodCreate) createSpec() (*Food, *sqlgraph.CreateSpec) {
	var (
		_node = &Food{config: fc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: food.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: food.FieldID,
			},
		}
	)
	if id, ok := fc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := fc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: food.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := fc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: food.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := fc.mutation.DeleteFlag(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: food.FieldDeleteFlag,
		})
		_node.DeleteFlag = value
	}
	if value, ok := fc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: food.FieldName,
		})
		_node.Name = value
	}
	return _node, _spec
}

// FoodCreateBulk is the builder for creating many Food entities in bulk.
type FoodCreateBulk struct {
	config
	builders []*FoodCreate
}

// Save creates the Food entities in the database.
func (fcb *FoodCreateBulk) Save(ctx context.Context) ([]*Food, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Food, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FoodMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				if nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FoodCreateBulk) SaveX(ctx context.Context) []*Food {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
